//list of enemies that spawn in spawners. Every spawner triggered will increase the difficulty of the area, meaning harder things will spawn.
spawns = {
  //library
  library: [
    ["gray"],
    ["red"],
    ["yellow"],
    ["blue"],
    ["blue_small"],
    ["pink"],
    ["green"],
    ["purple"],
    ["geode_1"],
    ["geode_2"],
    ["geode_3"],
    ["geode_4"],
  ],
  //spawns in the sewer one
  sewer2: [
    [],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    ["gray"],
    ["gray"],
    ["gray"],
    ["gray", "gray"],
    ["gray", "gray"],
    ["gray", "gray"],
    ["gray", "gray"],
    ["gray", "gray", "gray"],
    ["gray", "gray", "gray"],
    ["gray", "gray", "gray"],
    ["gray", "gray", "gray"],
    ["gray", "red"],
    ["gray", "red"],
    ["gray", "red"],
    ["gray", "red"],
    ["gray", "red", "gray"],
    ["gray", "red", "gray"],
    ["gray", "red", "gray"],
    ["gray", "red", "gray"],
    ["gray", "red", "gray", "red"],
    ["gray", "red", "gray", "red"],
    ["gray", "red", "gray", "red"],
    ["gray", "red", "gray", "red"],
    ["gray", "red", "gray", "red"],
    ["gray", "red", "gray", "red"],
    ["gray", "red", "gray", "red"],
    ["gray", "red", "gray", "red"],
    ["gray", "gray", "yellow", "gray"],
    ["gray", "gray", "yellow", "gray"],
    ["gray", "gray", "yellow", "gray"],
    ["gray", "gray", "yellow", "gray"],
    ["gray", "gray", "yellow", "gray"],
    ["gray", "gray", "yellow", "gray"],
    ["gray", "gray", "yellow", "gray"],
    ["gray", "gray", "yellow", "gray"],
    ["gray", "yellow", "red", "gray"],
    ["gray", "yellow", "red", "gray"],
    ["gray", "yellow", "red", "gray"],
    ["gray", "yellow", "red", "gray"],
    ["red", "yellow", "red", "yellow"],
    ["red", "yellow", "red", "yellow"],
    ["red", "yellow", "red", "yellow"],
    ["red", "yellow", "red", "yellow"],
    ["gray", "red", "gray", "blue"],
    ["gray", "red", "gray", "blue"],
    ["gray", "red", "gray", "blue"],
    ["gray", "red", "gray", "blue"],
    ["gray", "red", "gray", "blue"],
    ["gray", "red", "gray", "blue"],
    ["gray", "red", "gray", "blue"],
    ["gray", "red", "gray", "blue"],
    ["gray", "red", "red", "blue"],
    ["gray", "red", "red", "blue"],
    ["gray", "red", "red", "blue"],
    ["gray", "red", "red", "blue"],
    ["gray", "red", "red", "blue"],
    ["gray", "red", "red", "blue"],
    ["gray", "red", "red", "blue"],
    ["gray", "red", "red", "blue"],
    ["red", "blue", "yellow", "red"],
    ["red", "blue", "yellow", "red"],
    ["red", "blue", "yellow", "red"],
    ["red", "blue", "yellow", "red"],
    ["red", "blue", "yellow", "red"],
    ["red", "blue", "yellow", "red"],
    ["red", "blue", "yellow", "red"],
    ["red", "blue", "yellow", "red"],
    ["gray", "blue", "blue", "pink"],
    ["gray", "blue", "blue", "pink"],
    ["gray", "blue", "blue", "pink"],
    ["gray", "blue", "blue", "pink"],
    ["blue", "yellow", "red", "pink"],
    ["blue", "yellow", "red", "pink"],
    ["blue", "yellow", "red", "pink"],
    ["blue", "yellow", "red", "pink"],
    ["blue", "yellow", "red", "gray", "pink"],
    ["blue", "yellow", "red", "gray", "pink"],
    ["blue", "yellow", "red", "gray", "pink"],
    ["blue", "yellow", "red", "gray", "pink"],
    ["blue", "yellow", "red", "red", "pink"],
    ["blue", "yellow", "red", "red", "pink"],
    ["blue", "yellow", "red", "red", "pink"],
    ["blue", "yellow", "red", "red", "pink"],
    ["blue", "yellow", "red", "red", "pink", "yellow"],
    ["blue", "yellow", "red", "red", "pink", "yellow"],
    ["blue", "yellow", "red", "red", "pink", "yellow"],
    ["blue", "yellow", "red", "red", "pink", "yellow"],
    ["blue", "yellow", "red", "red", "pink", "yellow"],
    ["blue", "yellow", "red", "red", "pink", "yellow"],
    ["blue", "yellow", "red", "red", "pink", "yellow"],
    ["blue", "yellow", "red", "red", "pink", "yellow"],
    ["blue", "yellow", "blue", "red", "pink", "green"],
    ["blue", "yellow", "blue", "red", "pink", "green"],
    ["blue", "yellow", "blue", "red", "pink", "green"],
    ["blue", "yellow", "blue", "red", "pink", "green"],
    ["blue", "yellow", "blue", "red", "pink", "green"],
    ["blue", "yellow", "blue", "red", "pink", "green"],
    ["blue", "yellow", "blue", "red", "pink", "green"],
    ["blue", "yellow", "blue", "red", "pink", "green"],
    ["blue", "pink", "blue", "red", "red", "green"],
    ["blue", "pink", "blue", "red", "red", "green"],
    ["blue", "pink", "blue", "red", "red", "green"],
    ["blue", "pink", "blue", "red", "red", "green"],
    ["blue", "pink", "blue", "red", "red", "green"],
    ["blue", "pink", "blue", "red", "red", "green"],
    ["blue", "pink", "blue", "red", "red", "green"],
    ["blue", "pink", "blue", "red", "red", "green"],
    ["blue", "yellow", "blue", "red", "red", "yellow", "pink"],
    ["blue", "yellow", "blue", "red", "red", "yellow", "pink"],
    ["blue", "yellow", "blue", "red", "red", "yellow", "pink"],
    ["blue", "yellow", "blue", "red", "red", "yellow", "pink"],
    ["blue", "yellow", "blue", "red", "red", "yellow", "pink"],
    ["blue", "yellow", "blue", "red", "red", "yellow", "pink"],
    ["blue", "yellow", "blue", "red", "red", "yellow", "pink"],
    ["blue", "yellow", "blue", "red", "red", "yellow", "pink"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "green", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "blue", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "blue", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "blue", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "blue", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "blue", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "blue", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "blue", "yellow", "blue", "yellow"],
    ["blue", "yellow", "blue", "green", "blue", "yellow", "blue", "yellow"],
    ["gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray"],
    ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "green"],
    ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "green"],
    ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "green"],
    ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "green"],
    ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "green"],
    ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "green"],
    ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "green"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue", "blue"],
    ["blue", "green", "blue", "blue", "blue", "yellow", "blue", "green", "blue", "blue","blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
    ],
  //spawns in the sewer one
  sewer1: [
      [],
      [],
      [],
      [],
      ["gray"],
      [],
      [],
      ["gray"],
      [],
      [],
      ["gray"],
      [],
      [],
      ["gray"],
      [],
      [],
      ["gray"],
      [],
      [],
      ["gray"],
      [],
      [],
      ["gray"],
      [],
      [],
      ["gray"],
      [],
      ["gray"],
      [],
      ["gray"],
      [],
      ["gray"],
      [],
      ["gray"],
      [],
      ["gray"],
      [],
      ["gray"],
      [],
      ["gray"],
      [],
      ["gray"],
      [],
      ["gray"],
      ["gray"],
      ["gray"],
      ["gray"],
      ["gray"],
      ["gray"],
      ["gray"],
      ["gray"],
      ["gray", "gray"],
      ["gray", "gray"],
      ["gray", "gray"],
      ["gray", "gray"],
      ["gray", "gray"],
      ["gray", "gray"],
      ["gray", "gray"],
      ["gray", "gray"],
      ["gray", "gray", "gray"],
      ["gray", "gray", "gray"],
      ["gray", "gray", "gray"],
      ["gray", "gray", "gray"],
      ["gray", "gray", "gray"],
      ["gray", "gray", "gray"],
      ["gray", "gray", "gray"],
      ["gray", "gray", "gray"],
      ["gray", "red"],
      ["gray", "red"],
      ["gray", "red"],
      ["gray", "red"],
      ["gray", "red"],
      ["gray", "red"],
      ["gray", "red"],
      ["gray", "red", "gray"],
      ["gray", "red", "gray"],
      ["gray", "red", "gray"],
      ["gray", "red", "gray"],
      ["gray", "red", "gray"],
      ["gray", "red", "gray"],
      ["gray", "red", "gray"],
      ["gray", "red", "gray"],
      ["gray", "red", "gray", "gray"],
      ["gray", "red", "gray", "gray"],
      ["gray", "red", "gray", "gray"],
      ["gray", "red", "gray", "gray"],
      ["gray", "red", "gray", "gray"],
      ["gray", "red", "gray", "gray"],
      ["gray", "red", "gray", "gray"],
      ["gray", "red", "gray", "gray"],
      ["gray", "red", "gray", "red"],
      ["gray", "red", "gray", "red"],
      ["gray", "red", "gray", "red"],
      ["gray", "red", "gray", "red"],
      ["gray", "red", "gray", "red"],
      ["gray", "red", "gray", "red"],
      ["gray", "red", "gray", "red"],
      ["gray", "red", "gray", "red"],
      ["gray", "gray", "yellow", "gray"],
      ["gray", "gray", "yellow", "gray"],
      ["gray", "gray", "yellow", "gray"],
      ["gray", "gray", "yellow", "gray"],
      ["gray", "gray", "yellow", "gray"],
      ["gray", "gray", "yellow", "gray"],
      ["gray", "gray", "yellow", "gray"],
      ["gray", "gray", "yellow", "gray"],
      ["gray", "yellow", "red", "gray"],
      ["gray", "yellow", "red", "gray"],
      ["gray", "yellow", "red", "gray"],
      ["gray", "yellow", "red", "gray"],
      ["gray", "yellow", "red", "gray"],
      ["gray", "yellow", "red", "gray"],
      ["gray", "yellow", "red", "gray"],
      ["gray", "yellow", "red", "gray"],
      ["gray", "yellow", "red", "red"],
      ["gray", "yellow", "red", "red"],
      ["gray", "yellow", "red", "red"],
      ["gray", "yellow", "red", "red"],
      ["gray", "yellow", "red", "red"],
      ["gray", "yellow", "red", "red"],
      ["gray", "yellow", "red", "red"],
      ["gray", "yellow", "red", "red"],
      ["red", "red", "red", "red"],
      ["red", "red", "red", "red"],
      ["red", "red", "red", "red"],
      ["red", "red", "red", "red"],
      ["red", "red", "red", "red"],
      ["red", "red", "red", "red"],
      ["red", "red", "red", "red"],
      ["red", "red", "red", "red"],
      ["red", "yellow", "red", "yellow"],
      ["red", "yellow", "red", "yellow"],
      ["red", "yellow", "red", "yellow"],
      ["red", "yellow", "red", "yellow"],
      ["red", "yellow", "red", "yellow"],
      ["red", "yellow", "red", "yellow"],
      ["red", "yellow", "red", "yellow"],
      ["red", "yellow", "red", "yellow"],
      ["gray", "red", "gray", "blue"],
      ["gray", "red", "gray", "blue"],
      ["gray", "red", "gray", "blue"],
      ["gray", "red", "gray", "blue"],
      ["gray", "red", "gray", "blue"],
      ["gray", "red", "gray", "blue"],
      ["gray", "red", "gray", "blue"],
      ["gray", "red", "gray", "blue"],
      ["gray", "red", "red", "blue"],
      ["gray", "red", "red", "blue"],
      ["gray", "red", "red", "blue"],
      ["gray", "red", "red", "blue"],
      ["gray", "red", "red", "blue"],
      ["gray", "red", "red", "blue"],
      ["gray", "red", "red", "blue"],
      ["gray", "red", "red", "blue"],
      ["blue", "red", "red", "red"],
      ["blue", "red", "red", "red"],
      ["blue", "red", "red", "red"],
      ["blue", "red", "red", "red"],
      ["blue", "red", "red", "red"],
      ["blue", "red", "red", "red"],
      ["blue", "red", "red", "red"],
      ["blue", "red", "red", "red"],
      ["red", "blue", "yellow", "red"],
      ["red", "blue", "yellow", "red"],
      ["red", "blue", "yellow", "red"],
      ["red", "blue", "yellow", "red"],
      ["red", "blue", "yellow", "red"],
      ["red", "blue", "yellow", "red"],
      ["red", "blue", "yellow", "red"],
      ["red", "blue", "yellow", "red"],
      ["gray", "blue", "blue", "gray"],
      ["gray", "blue", "blue", "gray"],
      ["gray", "blue", "blue", "gray"],
      ["gray", "blue", "blue", "gray"],
      ["gray", "blue", "blue", "gray"],
      ["gray", "blue", "blue", "gray"],
      ["gray", "blue", "blue", "gray"],
      ["gray", "blue", "blue", "gray"],
      ["blue", "yellow", "red", "gray"],
      ["blue", "yellow", "red", "gray"],
      ["blue", "yellow", "red", "gray"],
      ["blue", "yellow", "red", "gray"],
      ["blue", "yellow", "red", "gray"],
      ["blue", "yellow", "red", "gray"],
      ["blue", "yellow", "red", "gray"],
      ["blue", "yellow", "red", "gray"],
      ["blue", "yellow", "red", "gray", "gray"],
      ["blue", "yellow", "red", "gray", "gray"],
      ["blue", "yellow", "red", "gray", "gray"],
      ["blue", "yellow", "red", "gray", "gray"],
      ["blue", "yellow", "red", "gray", "gray"],
      ["blue", "yellow", "red", "gray", "gray"],
      ["blue", "yellow", "red", "gray", "gray"],
      ["blue", "yellow", "red", "gray", "gray"],
      ["blue", "yellow", "red", "red", "gray"],
      ["blue", "yellow", "red", "red", "gray"],
      ["blue", "yellow", "red", "red", "gray"],
      ["blue", "yellow", "red", "red", "gray"],
      ["blue", "yellow", "red", "red", "gray"],
      ["blue", "yellow", "red", "red", "gray"],
      ["blue", "yellow", "red", "red", "gray"],
      ["blue", "yellow", "red", "red", "gray"],
      ["blue", "yellow", "red", "red", "gray", "yellow"],
      ["blue", "yellow", "red", "red", "gray", "yellow"],
      ["blue", "yellow", "red", "red", "gray", "yellow"],
      ["blue", "yellow", "red", "red", "gray", "yellow"],
      ["blue", "yellow", "red", "red", "gray", "yellow"],
      ["blue", "yellow", "red", "red", "gray", "yellow"],
      ["blue", "yellow", "red", "red", "gray", "yellow"],
      ["blue", "yellow", "red", "red", "gray", "yellow"],
      ["blue", "yellow", "blue", "red", "gray", "yellow"],
      ["blue", "yellow", "blue", "red", "gray", "yellow"],
      ["blue", "yellow", "blue", "red", "gray", "yellow"],
      ["blue", "yellow", "blue", "red", "gray", "yellow"],
      ["blue", "yellow", "blue", "red", "gray", "yellow"],
      ["blue", "yellow", "blue", "red", "gray", "yellow"],
      ["blue", "yellow", "blue", "red", "gray", "yellow"],
      ["blue", "yellow", "blue", "red", "gray", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
      ["gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
      ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue","blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"]
  ],
  //spawns in the debug level
  debugArea: [
  [],
  [],
  [],
  [],
  ["gray"],
  [],
  [],
  ["gray"],
  [],
  [],
  ["gray"],
  [],
  [],
  ["gray"],
  [],
  [],
  ["gray"],
  [],
  [],
  ["gray"],
  [],
  [],
  ["gray"],
  [],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue","blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ],

  //spawns in the black market
  blackMarket: [
    ["red"],
    ["red", "green"],
    ["red", "red", "green"],
    ["red", "red", "red", "green"],
    ["red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
  ],
  //spawns in the desert
  desert: [
    ["gray"],
    ["yellow"],
    ["gray", "gray"],
    ["yellow", "gray"],
    ["yellow", "yellow"],
    ["pink", "yellow"],
    ["pink", "pink"],
    ["purple", "pink"],
    ["purple", "purple"],
    ["gray", "gray", "gray"],
    ["yellow", "gray", "gray"],
    ["yellow", "yellow", "gray"],
    ["yellow", "yellow", "yellow"],
    ["pink", "yellow", "yellow"],
    ["pink", "pink", "yellow"],
    ["pink", "pink", "pink"],
    ["purple", "pink", "pink"],
    ["purple", "purple", "pink"],
    ["purple", "purple", "purple"],
    ["gray", "gray", "gray", "gray"],
    ["yellow", "gray", "gray", "gray"],
    ["yellow", "yellow", "gray", "gray"],
    ["yellow", "yellow", "yellow", "gray"],
    ["yellow", "yellow", "yellow", "yellow"],
    ["pink", "yellow", "yellow", "yellow"],
    ["pink", "pink", "yellow", "yellow"],
    ["pink", "pink", "pink", "yellow"],
    ["pink", "pink", "pink", "pink"],
    ["purple", "pink", "pink", "pink"],
    ["purple", "purple", "pink", "pink"],
    ["purple", "purple", "purple", "pink"],
    ["purple", "purple", "purple", "purple"],
    ["gray", "gray", "gray", "gray", "gray"],
    ["yellow", "gray", "gray", "gray", "gray"],
    ["yellow", "yellow", "gray", "gray", "gray"],
    ["yellow", "yellow", "yellow", "gray", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "yellow"],
    ["pink", "pink", "pink", "pink", "pink"],
    ["purple", "pink", "pink", "pink", "pink"],
    ["purple", "purple", "pink", "pink", "pink"],
    ["purple", "purple", "purple", "pink", "pink"],
    ["purple", "purple", "purple", "purple", "pink"],
    ["purple", "purple", "purple", "purple", "purple"],
    ["gray", "gray", "gray", "gray", "gray", "gray"],
    ["yellow", "gray", "gray", "gray", "gray", "gray"],
    ["yellow", "yellow", "gray", "gray", "gray", "gray"],
    ["yellow", "yellow", "yellow", "gray", "gray", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "gray", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "yellow", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink"],
    ["purple", "pink", "pink", "pink", "pink", "pink"],
    ["purple", "purple", "pink", "pink", "pink", "pink"],
    ["purple", "purple", "purple", "pink", "pink", "pink"],
    ["purple", "purple", "purple", "purple", "pink", "pink"],
    ["purple", "purple", "purple", "purple", "purple", "pink"],
    ["purple", "purple", "purple", "purple", "purple", "purple"],
    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
    ["yellow", "gray", "gray", "gray", "gray", "gray", "gray"],
    ["yellow", "yellow", "gray", "gray", "gray", "gray", "gray"],
    ["yellow", "yellow", "yellow", "gray", "gray", "gray", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "gray", "gray", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "yellow", "gray", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "purple"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "purple", "purple"],
    ["purple", "pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "purple", "purple"],
    ["purple", "purple", "pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "purple", "purple"],
    ["purple", "purple", "purple", "pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "purple", "purple"],
  ]
}