//list of enemies that spawn in spawners. Every spawner triggered will increase the difficulty of the area, meaning harder things will spawn.
spawns = [
  //spawns in the debug level (only level for now)
  [
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ]
]