//list of enemies that spawn in spawners. Every spawner triggered will increase the difficulty of the area, meaning harder things will spawn.
spawns = {
  //library
  library: [
    ["gray"],
    ["red"],
    ["yellow"],
    ["blue"],
    ["blue_small"],
    ["pink"],
    ["green"],
    ["purple"],
    ["tan"],
    ["navy"],
    ["mustard"],
    ["geode_1"],
    ["geode_2"],
    ["geode_3"],
    ["geode_4"],
  ],
  cave4: [
    [],
  ],
  //spawns in the cave three
  cave3: [
    [],
    [],
    [],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    ["gray"],
    ["gray"],
    ["gray"],
    ["gray", "gray"],
    ["gray"],
    ["gray", "gray"],
    ["gray"],
    ["yellow", "gray"],
    ["gray"],
    ["yellow", "gray"],
    ["gray"],
    ["yellow", "gray"],
    ["yellow"],
    ["yellow", "gray"],
    ["yellow"],
    ["yellow", "gray"],
    ["mustard"],
    ["yellow", "gray"],
    ["purple"],
    ["yellow", "gray"],
    ["purple"],
    ["yellow", "gray"],
    ["navy", "mustard"],
    ["yellow", "gray"],
    ["navy", "gray", "mustard"],
    ["yellow", "gray"],
    ["navy", "gray", "mustard"],
    ["yellow", "navy"],
    ["navy", "purple", "mustard"],
    ["yellow", "navy"],
    ["navy", "purple", "mustard"],
    ["yellow", "gray", "navy", "tan"],
    ["purple", "gray", "gray"],
    ["yellow", "gray", "navy", "tan"],
    ["purple", "gray", "gray"],
    ["yellow", "yellow", "navy", "tan"],
    ["purple", "gray", "gray"],
    ["yellow", "yellow", "navy", "tan"],
    ["purple", "gray", "gray"],
    ["yellow", "yellow", "navy", "tan", "mustard"],
    ["purple", "gray", "gray"],
    ["yellow", "yellow", "navy", "tan", "mustard"],
    ["purple", "gray", "gray"],
    ["yellow", "yellow", "navy", "tan", "mustard"],
    ["purple", "gray", "gray", "gray"],
    ["yellow", "yellow", "navy", "tan", "mustard"],
    ["purple", "gray", "gray", "gray"],
    ["yellow", "yellow", "navy", "navy"],
    ["purple", "gray", "tan", "gray"],
    ["yellow", "yellow", "navy", "navy"],
    ["purple", "gray", "tan", "gray", "mustard"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "gray", "tan", "gray", "mustard"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "gray", "tan", "gray", "mustard"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "gray", "tan", "navy"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "gray", "tan", "navy"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "yellow", "tan", "navy", "mustard"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "yellow", "tan", "navy", "mustard"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "navy", "tan", "navy", "mustard"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "navy", "tan", "navy"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "navy", "tan", "navy", "mustard"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "navy", "tan", "navy", "mustard"],
    ["yellow", "yellow", "navy", "yellow", "mustard"],
    ["purple", "yellow", "tan", "navy", "mustard"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "yellow", "tan", "navy", "mustard"],
  ],
  //spawns in the cave two
  cave2: [
    [],
    [],
    [],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    ["gray"],
    ["gray"],
    ["gray"],
    ["gray", "gray"],
    ["gray"],
    ["gray", "gray"],
    ["gray"],
    ["yellow", "gray"],
    ["gray"],
    ["yellow", "gray"],
    ["gray"],
    ["yellow", "gray"],
    ["yellow"],
    ["yellow", "gray"],
    ["yellow"],
    ["yellow", "gray"],
    ["navy"],
    ["yellow", "gray"],
    ["purple"],
    ["yellow", "gray"],
    ["purple"],
    ["yellow", "gray"],
    ["navy"],
    ["yellow", "gray"],
    ["navy", "gray"],
    ["yellow", "gray"],
    ["navy", "gray"],
    ["yellow", "navy"],
    ["navy", "purple"],
    ["yellow", "navy"],
    ["navy", "purple"],
    ["yellow", "gray", "navy", "tan"],
    ["purple", "gray", "gray"],
    ["yellow", "gray", "navy", "tan"],
    ["purple", "gray", "gray"],
    ["yellow", "yellow", "navy", "tan"],
    ["purple", "gray", "gray"],
    ["yellow", "yellow", "navy", "tan"],
    ["purple", "gray", "gray"],
    ["yellow", "yellow", "navy", "tan"],
    ["purple", "gray", "gray"],
    ["yellow", "yellow", "navy", "tan"],
    ["purple", "gray", "gray"],
    ["yellow", "yellow", "navy", "tan"],
    ["purple", "gray", "gray", "gray"],
    ["yellow", "yellow", "navy", "tan"],
    ["purple", "gray", "gray", "gray"],
    ["yellow", "yellow", "navy", "navy"],
    ["purple", "gray", "tan", "gray"],
    ["yellow", "yellow", "navy", "navy"],
    ["purple", "gray", "tan", "gray"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "gray", "tan", "gray"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "gray", "tan", "gray"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "gray", "tan", "navy"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "gray", "tan", "navy"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "yellow", "tan", "navy"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "yellow", "tan", "navy"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "navy", "tan", "navy"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "navy", "tan", "navy"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "navy", "tan", "navy"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "navy", "tan", "navy"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "yellow", "tan", "navy"],
    ["yellow", "yellow", "navy", "yellow"],
    ["purple", "yellow", "tan", "navy"],
    ],
  //spawns in the cave one
  cave1: [
      [],
      [],
      [],
      [],
      ["gray"],
      [],
      ["gray"],
      [],
      ["gray"],
      [],
      ["gray"],
      [],
      ["gray"],
      ["gray"],
      ["gray"],
      ["gray"],
      ["gray", "gray"],
      ["gray"],
      ["gray", "gray"],
      ["gray"],
      ["yellow", "gray"],
      ["gray"],
      ["yellow", "gray"],
      ["gray"],
      ["yellow", "gray"],
      ["yellow"],
      ["yellow", "gray"],
      ["yellow"],
      ["yellow", "gray"],
      ["navy"],
      ["yellow", "gray"],
      ["navy"],
      ["yellow", "gray"],
      ["navy"],
      ["yellow", "gray"],
      ["navy"],
      ["yellow", "gray"],
      ["navy", "gray"],
      ["yellow", "gray"],
      ["navy", "gray"],
      ["yellow", "navy"],
      ["navy", "gray"],
      ["yellow", "navy"],
      ["navy", "gray"],
      ["yellow", "gray", "navy"],
      ["navy", "gray", "gray"],
      ["yellow", "gray", "navy"],
      ["navy", "gray", "gray"],
      ["yellow", "yellow", "navy"],
      ["navy", "gray", "gray"],
      ["yellow", "yellow", "navy"],
      ["navy", "gray", "gray"],
      ["yellow", "yellow", "navy"],
      ["navy", "gray", "gray"],
      ["yellow", "yellow", "navy"],
      ["navy", "gray", "gray"],
      ["yellow", "yellow", "navy", "gray"],
      ["navy", "gray", "gray", "gray"],
      ["yellow", "yellow", "navy", "gray"],
      ["navy", "gray", "gray", "gray"],
      ["yellow", "yellow", "navy", "navy"],
      ["navy", "gray", "gray", "gray"],
      ["yellow", "yellow", "navy", "navy"],
      ["navy", "gray", "gray", "gray"],
      ["yellow", "yellow", "navy", "yellow"],
      ["navy", "gray", "gray", "gray"],
      ["yellow", "yellow", "navy", "yellow"],
      ["navy", "gray", "gray", "gray"],
      ["yellow", "yellow", "navy", "yellow"],
      ["navy", "gray", "gray", "navy"],
      ["yellow", "yellow", "navy", "yellow"],
      ["navy", "gray", "gray", "navy"],
      ["yellow", "yellow", "navy", "yellow"],
      ["navy", "yellow", "gray", "navy"],
      ["yellow", "yellow", "navy", "yellow"],
      ["navy", "yellow", "gray", "navy"],
      ["yellow", "yellow", "navy", "yellow"],
      ["navy", "navy", "gray", "navy"],
      ["yellow", "yellow", "navy", "yellow"],
      ["navy", "navy", "gray", "navy"],
      ["yellow", "yellow", "navy", "yellow"],
      ["navy", "navy", "yellow", "navy"],
      ["yellow", "yellow", "navy", "yellow"],
      ["navy", "navy", "yellow", "navy"],
      ["yellow", "yellow", "navy", "yellow"],
      ["navy", "yellow", "yellow", "navy"],
      ["yellow", "yellow", "navy", "yellow"],
      ["navy", "yellow", "yellow", "navy"],
  ],
  //spawns in the sewer four (boss)
  sewer4: [
    [],
  ],
  //spawns in the sewer three
  sewer3: [
    [],
    [],
    [],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    ["gray"],
    ["gray"],
    ["gray"],
    ["gray", "gray"],
    ["gray"],
    ["gray", "gray"],
    ["gray"],
    ["red", "gray"],
    ["gray"],
    ["red", "gray"],
    ["gray"],
    ["red", "gray"],
    ["red"],
    ["red", "gray"],
    ["red"],
    ["red", "gray"],
    ["green"],
    ["red", "gray"],
    ["blue"],
    ["red", "gray"],
    ["blue"],
    ["red", "gray"],
    ["yellow", "green"],
    ["red", "gray"],
    ["yellow", "gray", "green"],
    ["red", "gray"],
    ["yellow", "gray", "green"],
    ["red", "yellow"],
    ["yellow", "blue", "green"],
    ["red", "yellow"],
    ["yellow", "blue", "green"],
    ["red", "gray", "yellow", "pink"],
    ["blue", "gray", "gray"],
    ["red", "gray", "yellow", "pink"],
    ["blue", "gray", "gray"],
    ["red", "red", "yellow", "pink"],
    ["blue", "gray", "gray"],
    ["red", "red", "yellow", "pink"],
    ["blue", "gray", "gray"],
    ["red", "red", "yellow", "pink", "green"],
    ["blue", "gray", "gray"],
    ["red", "red", "yellow", "pink", "green"],
    ["blue", "gray", "gray"],
    ["red", "red", "yellow", "pink", "green"],
    ["blue", "gray", "gray", "gray"],
    ["red", "red", "yellow", "pink", "green"],
    ["blue", "gray", "gray", "gray"],
    ["red", "red", "yellow", "yellow"],
    ["blue", "gray", "pink", "gray"],
    ["red", "red", "yellow", "yellow"],
    ["blue", "gray", "pink", "gray", "green"],
    ["red", "red", "yellow", "red"],
    ["blue", "gray", "pink", "gray", "green"],
    ["red", "red", "yellow", "red"],
    ["blue", "gray", "pink", "gray", "green"],
    ["red", "red", "yellow", "red"],
    ["blue", "gray", "pink", "yellow"],
    ["red", "red", "yellow", "red"],
    ["blue", "gray", "pink", "yellow"],
    ["red", "red", "yellow", "red"],
    ["blue", "red", "pink", "yellow", "green"],
    ["red", "red", "yellow", "red"],
    ["blue", "red", "pink", "yellow", "green"],
    ["red", "red", "yellow", "red"],
    ["blue", "yellow", "pink", "yellow", "green"],
    ["red", "red", "yellow", "red"],
    ["blue", "yellow", "pink", "yellow"],
    ["red", "red", "yellow", "red"],
    ["blue", "yellow", "pink", "yellow", "green"],
    ["red", "red", "yellow", "red"],
    ["blue", "yellow", "pink", "yellow", "green"],
    ["red", "red", "yellow", "red", "green"],
    ["blue", "red", "pink", "yellow", "green"],
    ["red", "red", "yellow", "red"],
    ["blue", "red", "pink", "yellow", "green"],
  ],
  //spawns in the sewer two
  sewer2: [
    [],
    [],
    [],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    [],
    ["gray"],
    ["gray"],
    ["gray"],
    ["gray"],
    ["gray", "gray"],
    ["gray"],
    ["gray", "gray"],
    ["gray"],
    ["red", "gray"],
    ["gray"],
    ["red", "gray"],
    ["gray"],
    ["red", "gray"],
    ["red"],
    ["red", "gray"],
    ["red"],
    ["red", "gray"],
    ["yellow"],
    ["red", "gray"],
    ["blue"],
    ["red", "gray"],
    ["blue"],
    ["red", "gray"],
    ["yellow"],
    ["red", "gray"],
    ["yellow", "gray"],
    ["red", "gray"],
    ["yellow", "gray"],
    ["red", "yellow"],
    ["yellow", "blue"],
    ["red", "yellow"],
    ["yellow", "blue"],
    ["red", "gray", "yellow", "pink"],
    ["blue", "gray", "gray"],
    ["red", "gray", "yellow", "pink"],
    ["blue", "gray", "gray"],
    ["red", "red", "yellow", "pink"],
    ["blue", "gray", "gray"],
    ["red", "red", "yellow", "pink"],
    ["blue", "gray", "gray"],
    ["red", "red", "yellow", "pink"],
    ["blue", "gray", "gray"],
    ["red", "red", "yellow", "pink"],
    ["blue", "gray", "gray"],
    ["red", "red", "yellow", "pink"],
    ["blue", "gray", "gray", "gray"],
    ["red", "red", "yellow", "pink"],
    ["blue", "gray", "gray", "gray"],
    ["red", "red", "yellow", "yellow"],
    ["blue", "gray", "pink", "gray"],
    ["red", "red", "yellow", "yellow"],
    ["blue", "gray", "pink", "gray"],
    ["red", "red", "yellow", "red"],
    ["blue", "gray", "pink", "gray"],
    ["red", "red", "yellow", "red"],
    ["blue", "gray", "pink", "gray"],
    ["red", "red", "yellow", "red"],
    ["blue", "gray", "pink", "yellow"],
    ["red", "red", "yellow", "red"],
    ["blue", "gray", "pink", "yellow"],
    ["red", "red", "yellow", "red"],
    ["blue", "red", "pink", "yellow"],
    ["red", "red", "yellow", "red"],
    ["blue", "red", "pink", "yellow"],
    ["red", "red", "yellow", "red"],
    ["blue", "yellow", "pink", "yellow"],
    ["red", "red", "yellow", "red"],
    ["blue", "yellow", "pink", "yellow"],
    ["red", "red", "yellow", "red"],
    ["blue", "yellow", "pink", "yellow"],
    ["red", "red", "yellow", "red"],
    ["blue", "yellow", "pink", "yellow"],
    ["red", "red", "yellow", "red"],
    ["blue", "red", "pink", "yellow"],
    ["red", "red", "yellow", "red"],
    ["blue", "red", "pink", "yellow"],
    ],
  //spawns in the sewer one
  sewer1: [
      [],
      [],
      [],
      [],
      ["gray"],
      [],
      ["gray"],
      [],
      ["gray"],
      [],
      ["gray"],
      [],
      ["gray"],
      ["gray"],
      ["gray"],
      ["gray"],
      ["gray", "gray"],
      ["gray"],
      ["gray", "gray"],
      ["gray"],
      ["red", "gray"],
      ["gray"],
      ["red", "gray"],
      ["gray"],
      ["red", "gray"],
      ["red"],
      ["red", "gray"],
      ["red"],
      ["red", "gray"],
      ["yellow"],
      ["red", "gray"],
      ["yellow"],
      ["red", "gray"],
      ["yellow"],
      ["red", "gray"],
      ["yellow"],
      ["red", "gray"],
      ["yellow", "gray"],
      ["red", "gray"],
      ["yellow", "gray"],
      ["red", "yellow"],
      ["yellow", "gray"],
      ["red", "yellow"],
      ["yellow", "gray"],
      ["red", "gray", "yellow"],
      ["yellow", "gray", "gray"],
      ["red", "gray", "yellow"],
      ["yellow", "gray", "gray"],
      ["red", "red", "yellow"],
      ["yellow", "gray", "gray"],
      ["red", "red", "yellow"],
      ["yellow", "gray", "gray"],
      ["red", "red", "yellow"],
      ["yellow", "gray", "gray"],
      ["red", "red", "yellow"],
      ["yellow", "gray", "gray"],
      ["red", "red", "yellow", "gray"],
      ["yellow", "gray", "gray", "gray"],
      ["red", "red", "yellow", "gray"],
      ["yellow", "gray", "gray", "gray"],
      ["red", "red", "yellow", "yellow"],
      ["yellow", "gray", "gray", "gray"],
      ["red", "red", "yellow", "yellow"],
      ["yellow", "gray", "gray", "gray"],
      ["red", "red", "yellow", "red"],
      ["yellow", "gray", "gray", "gray"],
      ["red", "red", "yellow", "red"],
      ["yellow", "gray", "gray", "gray"],
      ["red", "red", "yellow", "red"],
      ["yellow", "gray", "gray", "yellow"],
      ["red", "red", "yellow", "red"],
      ["yellow", "gray", "gray", "yellow"],
      ["red", "red", "yellow", "red"],
      ["yellow", "red", "gray", "yellow"],
      ["red", "red", "yellow", "red"],
      ["yellow", "red", "gray", "yellow"],
      ["red", "red", "yellow", "red"],
      ["yellow", "yellow", "gray", "yellow"],
      ["red", "red", "yellow", "red"],
      ["yellow", "yellow", "gray", "yellow"],
      ["red", "red", "yellow", "red"],
      ["yellow", "yellow", "red", "yellow"],
      ["red", "red", "yellow", "red"],
      ["yellow", "yellow", "red", "yellow"],
      ["red", "red", "yellow", "red"],
      ["yellow", "red", "red", "yellow"],
      ["red", "red", "yellow", "red"],
      ["yellow", "red", "red", "yellow"],
  ],
  //spawns in the debug level
  debugArea: [
  [],
  [],
  [],
  [],
  ["gray"],
  [],
  [],
  ["gray"],
  [],
  [],
  ["gray"],
  [],
  [],
  ["gray"],
  [],
  [],
  ["gray"],
  [],
  [],
  ["gray"],
  [],
  [],
  ["gray"],
  [],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  [],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "gray", "gray"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "gray"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "red", "gray", "red"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "gray", "yellow", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "gray"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["gray", "yellow", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "red", "red", "red"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["red", "yellow", "red", "yellow"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "gray", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["gray", "red", "red", "blue"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["red", "blue", "yellow", "red"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["gray", "blue", "blue", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "gray", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "red", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "gray", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "gray"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "red", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "red", "blue", "yellow", "blue", "yellow"],
  ["gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray","gray"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ["blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue","blue", "yellow", "blue", "blue", "blue", "yellow", "blue", "yellow", "blue", "blue"],
  ],

  //spawns in the black market
  blackMarket: [
    ["red"],
    ["red", "green"],
    ["red", "red", "green"],
    ["red", "red", "red", "green"],
    ["red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
    ["red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "green"],
  ],
  //spawns in the desert
  desert: [
    ["gray"],
    ["yellow"],
    ["gray", "gray"],
    ["yellow", "gray"],
    ["yellow", "yellow"],
    ["pink", "yellow"],
    ["pink", "pink"],
    ["purple", "pink"],
    ["purple", "purple"],
    ["gray", "gray", "gray"],
    ["yellow", "gray", "gray"],
    ["yellow", "yellow", "gray"],
    ["yellow", "yellow", "yellow"],
    ["pink", "yellow", "yellow"],
    ["pink", "pink", "yellow"],
    ["pink", "pink", "pink"],
    ["purple", "pink", "pink"],
    ["purple", "purple", "pink"],
    ["purple", "purple", "purple"],
    ["gray", "gray", "gray", "gray"],
    ["yellow", "gray", "gray", "gray"],
    ["yellow", "yellow", "gray", "gray"],
    ["yellow", "yellow", "yellow", "gray"],
    ["yellow", "yellow", "yellow", "yellow"],
    ["pink", "yellow", "yellow", "yellow"],
    ["pink", "pink", "yellow", "yellow"],
    ["pink", "pink", "pink", "yellow"],
    ["pink", "pink", "pink", "pink"],
    ["purple", "pink", "pink", "pink"],
    ["purple", "purple", "pink", "pink"],
    ["purple", "purple", "purple", "pink"],
    ["purple", "purple", "purple", "purple"],
    ["gray", "gray", "gray", "gray", "gray"],
    ["yellow", "gray", "gray", "gray", "gray"],
    ["yellow", "yellow", "gray", "gray", "gray"],
    ["yellow", "yellow", "yellow", "gray", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "yellow"],
    ["pink", "pink", "pink", "pink", "pink"],
    ["purple", "pink", "pink", "pink", "pink"],
    ["purple", "purple", "pink", "pink", "pink"],
    ["purple", "purple", "purple", "pink", "pink"],
    ["purple", "purple", "purple", "purple", "pink"],
    ["purple", "purple", "purple", "purple", "purple"],
    ["gray", "gray", "gray", "gray", "gray", "gray"],
    ["yellow", "gray", "gray", "gray", "gray", "gray"],
    ["yellow", "yellow", "gray", "gray", "gray", "gray"],
    ["yellow", "yellow", "yellow", "gray", "gray", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "gray", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "yellow", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink"],
    ["purple", "pink", "pink", "pink", "pink", "pink"],
    ["purple", "purple", "pink", "pink", "pink", "pink"],
    ["purple", "purple", "purple", "pink", "pink", "pink"],
    ["purple", "purple", "purple", "purple", "pink", "pink"],
    ["purple", "purple", "purple", "purple", "purple", "pink"],
    ["purple", "purple", "purple", "purple", "purple", "purple"],
    ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
    ["yellow", "gray", "gray", "gray", "gray", "gray", "gray"],
    ["yellow", "yellow", "gray", "gray", "gray", "gray", "gray"],
    ["yellow", "yellow", "yellow", "gray", "gray", "gray", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "gray", "gray", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "yellow", "gray", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "gray"],
    ["yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "purple"],
    ["pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "purple", "purple"],
    ["purple", "pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "purple", "purple"],
    ["purple", "purple", "pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "purple", "purple"],
    ["purple", "purple", "purple", "pink", "pink", "pink", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "purple", "purple"],
  ]
}